CREATE  TABLE "public".ciudad ( 
	id_ciudad            integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nombre_ciudad        varchar(255)   ,
	precio_envio         float8   ,
	CONSTRAINT ciudad_pkey PRIMARY KEY ( id_ciudad )
 );

CREATE  TABLE "public".cliente ( 
	cedula_cliente       integer  NOT NULL ,
	nombre_cliente       varchar(255)   ,
	apellido_cliente     varchar(255)   ,
	telefono_cliente     varchar(255)   ,
	correo_cliente       varchar(255)   ,
	trabajo_cliente      varchar(255)   ,
	ciudad_cliente       varchar(255)   ,
	cod_sucursal         varchar(255)   ,
	CONSTRAINT cliente_pkey PRIMARY KEY ( cedula_cliente )
 );

CREATE  TABLE "public".peso ( 
	dimension_paquete    varchar(255)  NOT NULL ,
	peso_paquete         float8   ,
	precio_peso          float8   ,
	CONSTRAINT peso_pkey PRIMARY KEY ( dimension_paquete )
 );

CREATE  TABLE "public".sucursal ( 
	cod_sucursal         varchar(255)  NOT NULL ,
	direccion_sucursal   varchar(255)   ,
	telefono_sucursal    varchar(255)   ,
	id_ciudad            integer   ,
	CONSTRAINT sucursal_pkey PRIMARY KEY ( cod_sucursal )
 );

CREATE  TABLE "public".urgencia ( 
	nivel_urgencia       varchar(255)  NOT NULL ,
	descrip_urgencia     varchar(255)   ,
	precio_urgencia      float8   ,
	CONSTRAINT urgencia_pkey PRIMARY KEY ( nivel_urgencia )
 );

CREATE  TABLE "public".paquete ( 
	cod_paquete          varchar(255)  NOT NULL ,
	descrip_paquete      varchar(255)   ,
	usuario_destinatario varchar(255)   ,
	valor_declarativo    varchar(255)   ,
	fecha_ingreso        date   ,
	fecha_salida         date   ,
	ciudad_final         integer   ,
	cedula_cliente       integer   ,
	cod_sucursal         varchar(255)   ,
	CONSTRAINT paquete_pkey PRIMARY KEY ( cod_paquete )
 );

CREATE  TABLE "public".promocion ( 
	id_promocion         integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	descrip_promocion    varchar(255)   ,
	descuento_promocion  float8   ,
	cod_sucursal         varchar(255)   ,
	CONSTRAINT promocion_pkey PRIMARY KEY ( id_promocion )
 );

CREATE  TABLE "public".factura ( 
	ruc_factura          varchar(255)  NOT NULL ,
	fecha_factura        date   ,
	cod_paquete          varchar(255)   ,
	cedula_cliente       integer   ,
	id_ciudad            integer   ,
	dimension_paquete    varchar(255)   ,
	nivel_urgencia       varchar(255)   ,
	id_promocion         integer   ,
	CONSTRAINT factura_pkey PRIMARY KEY ( ruc_factura )
 );

ALTER TABLE "public".factura ADD CONSTRAINT factura_id_ciudad_fkey FOREIGN KEY ( id_ciudad ) REFERENCES "public".ciudad( id_ciudad );

ALTER TABLE "public".factura ADD CONSTRAINT factura_cedula_cliente_fkey FOREIGN KEY ( cedula_cliente ) REFERENCES "public".cliente( cedula_cliente );

ALTER TABLE "public".factura ADD CONSTRAINT factura_cod_paquete_fkey FOREIGN KEY ( cod_paquete ) REFERENCES "public".paquete( cod_paquete );

ALTER TABLE "public".factura ADD CONSTRAINT factura_dimension_paquete_fkey FOREIGN KEY ( dimension_paquete ) REFERENCES "public".peso( dimension_paquete );

ALTER TABLE "public".factura ADD CONSTRAINT factura_id_promocion_fkey FOREIGN KEY ( id_promocion ) REFERENCES "public".promocion( id_promocion );

ALTER TABLE "public".factura ADD CONSTRAINT factura_nivel_urgencia_fkey FOREIGN KEY ( nivel_urgencia ) REFERENCES "public".urgencia( nivel_urgencia );

ALTER TABLE "public".paquete ADD CONSTRAINT paquete_ciudad_final_fkey FOREIGN KEY ( ciudad_final ) REFERENCES "public".ciudad( id_ciudad );

ALTER TABLE "public".paquete ADD CONSTRAINT paquete_cedula_cliente_fkey FOREIGN KEY ( cedula_cliente ) REFERENCES "public".cliente( cedula_cliente );

ALTER TABLE "public".paquete ADD CONSTRAINT paquete_cod_sucursal_fkey FOREIGN KEY ( cod_sucursal ) REFERENCES "public".sucursal( cod_sucursal );

ALTER TABLE "public".promocion ADD CONSTRAINT promocion_cod_sucursal_fkey FOREIGN KEY ( cod_sucursal ) REFERENCES "public".sucursal( cod_sucursal );

ALTER TABLE "public".sucursal ADD CONSTRAINT sucursal_id_ciudad_fkey FOREIGN KEY ( id_ciudad ) REFERENCES "public".ciudad( id_ciudad );
